//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.RestEvalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestEvalService.IRestEvalService")]
    public interface IRestEvalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/SubmitEval", ReplyAction="http://tempuri.org/IRestEvalService/SubmitEvalResponse")]
        EvalServiceLibrary.Eval SubmitEval(EvalServiceLibrary.Eval eval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/SubmitEval", ReplyAction="http://tempuri.org/IRestEvalService/SubmitEvalResponse")]
        System.Threading.Tasks.Task<EvalServiceLibrary.Eval> SubmitEvalAsync(EvalServiceLibrary.Eval eval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetEval", ReplyAction="http://tempuri.org/IRestEvalService/GetEvalResponse")]
        EvalServiceLibrary.Eval GetEval(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetEval", ReplyAction="http://tempuri.org/IRestEvalService/GetEvalResponse")]
        System.Threading.Tasks.Task<EvalServiceLibrary.Eval> GetEvalAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetAllEvals", ReplyAction="http://tempuri.org/IRestEvalService/GetAllEvalsResponse")]
        EvalServiceLibrary.Eval[] GetAllEvals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetAllEvals", ReplyAction="http://tempuri.org/IRestEvalService/GetAllEvalsResponse")]
        System.Threading.Tasks.Task<EvalServiceLibrary.Eval[]> GetAllEvalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetEvalsBySubmitter", ReplyAction="http://tempuri.org/IRestEvalService/GetEvalsBySubmitterResponse")]
        EvalServiceLibrary.Eval[] GetEvalsBySubmitter(string submitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/GetEvalsBySubmitter", ReplyAction="http://tempuri.org/IRestEvalService/GetEvalsBySubmitterResponse")]
        System.Threading.Tasks.Task<EvalServiceLibrary.Eval[]> GetEvalsBySubmitterAsync(string submitter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/RemoveEval", ReplyAction="http://tempuri.org/IRestEvalService/RemoveEvalResponse")]
        void RemoveEval(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestEvalService/RemoveEval", ReplyAction="http://tempuri.org/IRestEvalService/RemoveEvalResponse")]
        System.Threading.Tasks.Task RemoveEvalAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestEvalServiceChannel : Client.RestEvalService.IRestEvalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestEvalServiceClient : System.ServiceModel.ClientBase<Client.RestEvalService.IRestEvalService>, Client.RestEvalService.IRestEvalService {
        
        public RestEvalServiceClient() {
        }
        
        public RestEvalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestEvalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestEvalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestEvalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EvalServiceLibrary.Eval SubmitEval(EvalServiceLibrary.Eval eval) {
            return base.Channel.SubmitEval(eval);
        }
        
        public System.Threading.Tasks.Task<EvalServiceLibrary.Eval> SubmitEvalAsync(EvalServiceLibrary.Eval eval) {
            return base.Channel.SubmitEvalAsync(eval);
        }
        
        public EvalServiceLibrary.Eval GetEval(string id) {
            return base.Channel.GetEval(id);
        }
        
        public System.Threading.Tasks.Task<EvalServiceLibrary.Eval> GetEvalAsync(string id) {
            return base.Channel.GetEvalAsync(id);
        }
        
        public EvalServiceLibrary.Eval[] GetAllEvals() {
            return base.Channel.GetAllEvals();
        }
        
        public System.Threading.Tasks.Task<EvalServiceLibrary.Eval[]> GetAllEvalsAsync() {
            return base.Channel.GetAllEvalsAsync();
        }
        
        public EvalServiceLibrary.Eval[] GetEvalsBySubmitter(string submitter) {
            return base.Channel.GetEvalsBySubmitter(submitter);
        }
        
        public System.Threading.Tasks.Task<EvalServiceLibrary.Eval[]> GetEvalsBySubmitterAsync(string submitter) {
            return base.Channel.GetEvalsBySubmitterAsync(submitter);
        }
        
        public void RemoveEval(string id) {
            base.Channel.RemoveEval(id);
        }
        
        public System.Threading.Tasks.Task RemoveEvalAsync(string id) {
            return base.Channel.RemoveEvalAsync(id);
        }
    }
}
